### ISSUE TITLE
py 3.6 branch

### ISSUE THREAD

**Issue by jschueller** [conda-forge/python-feedstock#103]
hello,
I saw there's a prerelease branch, now 3.6.0 is out I guess we could have a 3.6 branch

**Comment by Nelthorim** [comment]
It's a work-in-process: #101

**Comment by jjhelmus** [comment]
#101 was merged and the python-3.6.0 packages are now available in the `conda-forge` channel for all platforms.  Typically we keep the latest version of a package in the `master` branch with older versions in branches.  Therefore there is no need for a `3.6` branch as the `master` branch covers this version.  A `3.5` branch has been created for future released/updates to Python 3.5.x.
