### ISSUE TITLE
3.5.3-1 include tk8.6 but tk8.5 is pinned

### ISSUE THREAD

**Issue by looooo** [conda-forge/python-feedstock#127]
when trying to build a library with win I get errors because there are two versions of tk available. One is directly shiped with the python packacge and this is 8.6.

**Comment by looooo** [comment]
I don't know if my problem is really related to this, but this seems quite strange to me.

**Comment by jjhelmus** [comment]
What platform (Windows, OS X, Linux) and version of Python are you seeing this issue with.  

The Windows version of Python 3.5.3-1 includes a version of tk 8.6 which is build and packaged with Python.  This is included in the official installer as well as the conda version.  Installing a separate tk package into a conda environment is not recommended.  

On OS X and Linux the tk package is separate from the Python package and is currently pinned at `8.5.x`.  This version mismatch is a bit odd but is in place to keep compatibility with the `defaults` channel.

**Comment by jakirkham** [comment]
Is `defaults` still pinned to `8.5.x` or have they gone to `8.6.x`?

**Comment by looooo** [comment]
win = windows, sorry
@jjhelmus thanks for clarification.

**Comment by jjhelmus** [comment]
`defaults` still seems to be pinned to `8.5.x`.

Closing this issue, feel free to re-open if you feel this has not been resolved.

**Comment by looooo** [comment]
@jjhelmus : I can't use the tk version which is shipped with python because there are no headers available... So maybe we can reopen this issue.
