### ISSUE TITLE
Package missing in current linux-64 channels (python 3.5)

### ISSUE THREAD

**Issue by lukepfister** [conda-forge/python-feedstock#14]
I'm getting an error any time I try to update/install a package using conda.

``` bash
((nsp)) fresnel ➜ ~  conda update --all
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .............
Solving package specifications ....
Warning: Package missing in current linux-64 channels: 
  - conda-forge::python 3.5* (target=conda-forge::python-3.5.1-0.tar.bz2), skipping
Fetching package metadata .............
Solving package specifications ....
Warning: Package missing in current linux-64 channels: 
  - conda-forge::python 3.5* (target=conda-forge::python-3.5.1-0.tar.bz2), skipping
Error: Package missing in current linux-64 channels: 
  - conda-forge::python 3.5* (target=conda-forge::python-3.5.1-0.tar.bz2)
```

I've tried forcing a reinstall of python: 
``` bash 
((nsp)) fresnel ➜ ~  conda install -f python=3.5
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .............
Solving package specifications .............

Package plan for installation in environment /home/luke/software/python/miniconda/envs/nsp:

The following NEW packages will be INSTALLED:

    python: 3.5.1-0 conda-forge

Proceed ([y]/n)? y

Pruning extracted packages from the cache ...
```

But then a `conda update --all` returns the same error as before.

**Comment by pelson** [comment]
That is quite a weird error. The distribution definitely exists for linux-64 on the conda-forge channel (https://anaconda.org/conda-forge/python/3.5.1/download/linux-64/python-3.5.1-0.tar.bz2). Could you provide your `conda info` output, as well as listing the packages in your environment?

**Comment by lukepfister** [comment]
I think the error has less to do with conda-forge and more to do with the current conda release candidate.  I reverted to conda 4.0.7 and things are better.

I'll try to get a MWE put together soon.

**Comment by pelson** [comment]
Ok. Thanks @lukepfister. Feel free to ping `@kalefranz` if you believe there is an issue with conda itself. He will definitely want to know.

Closing for now as there is nothing to be done here, but please reopen with the MWE when ready.

Cheers,
