### ISSUE TITLE
Error when install openssl

### ISSUE THREAD

**Issue by pcmagic** [conda-forge/python-feedstock#147]
None pkg can be installed to the conda env in my PC. The computer is offline, and the error messages are as follow:

$ conda install openssl --offline
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: 
Solving package specifications: .
Error:  Dependencies missing in current linux-64 channels: 
  - conda -> requests -> python 3.5* -> openssl 1.0.2d
  - conda -> python 3.5* -> openssl 1.0.2d
  - conda -> pycosat -> python 3.5* -> openssl 1.0.2d
  - conda -> conda-env -> python 3.5* -> openssl 1.0.2d
  - conda -> pyyaml -> python 3.5* -> openssl 1.0.2d
  - python 3.5* -> openssl 1.0.2d
  - requests (target=requests-2.9.1-py35_0.tar.bz2) -> python 3.5* -> openssl 1.0.2d
  - conda-env (target=conda-env-2.4.5-py35_0.tar.bz2) -> python 3.5* -> openssl 1.0.2d
  - pycosat (target=pycosat-0.6.1-py35_0.tar.bz2) -> python 3.5* -> openssl 1.0.2d
  - pyyaml (target=pyyaml-3.11-py35_1.tar.bz2) -> python 3.5* -> openssl 1.0.2d

**Comment by jjhelmus** [comment]
Can you provide more details on your setup.  I don't believe the python package provided on the `conda-forge` channel ever pinned openssl to 1.0.2d so I do not know where this dependency is coming from.

**Comment by pcmagic** [comment]
Thanks a lot for your reply. The follow is what I did. 
1). I have installed anaconda package in my computer A, developing a program to do some scientific simulation, i.e. bacterial locomotion at flows. 
2). Then, I installed a same version of anaconda in a offline computer, a supercomputer B after firewall. 
3). I then coppied A:PATH_ANACONDA/pkgs to B:PATH_ANACONDA/pkgs using scp. 
4). In computer B, run: conda update --all --offline

However, if I install a package like: python setup.py install, there is no error message.

**Comment by jakirkham** [comment]
Is this still an issue?

**Comment by zetaFairlight** [comment]
It's giving me and many more people similar problems...

**Comment by isuruf** [comment]
Old issue. Please re-open if the issue still happens
