### ISSUE TITLE
Python 3.7.0 in the prerelease label

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/python-feedstock#177]
It would be great to provide Python 3.7.0 package in the [prerelease label](https://anaconda.org/conda-forge/python/files?channel=prerelease).  

[PEP 537](https://www.python.org/dev/peps/pep-0537/) has the [release schedule](https://www.python.org/dev/peps/pep-0537/#release-schedule) for the new version:

```
Actual :
...
* 3.7.0 beta 3: 2018-03-29

Expected:

* 3.7.0 beta 4: 2018-04-30
* 3.7.0 candidate 1: 2018-05-21
* 3.7.0 candidate 2: 2018-06-04 (if necessary)
* 3.7.0 final: 2018-06-15
```

**Comment by scw** [comment]
I agree, this would be great. I just installed 3.7b2 "the old fashioned way" and it reminded me just how great conda (and conda-forge!) are for solving this kind of problem.

**Comment by jakirkham** [comment]
Closing as Python 3.7 has since been released in conda-forge.
