### ISSUE TITLE
Building Python 2.7 with tracemalloc support

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/python-feedstock#182]
The `tracemalloc` module is an extremely valuable feature in Python 3. It is possible to build Python 2 with `tracemalloc` support. Though it requires patching the Python 2 build. Raising this issue to see if this approach would be viable.

ref: http://pytracemalloc.readthedocs.io/install.html#manual-installation

**Comment by neonb88** [comment]
> ref: http://pytracemalloc.readthedocs.io/install.html#manual-installation

link is now dead

**Comment by jakirkham** [comment]
Probably because the author deleted it as part of [archiving the repo]( https://github.com/vstinner/pytracemalloc ).

In any event, while I'm sure this contribution would be welcome, there is no more active support of Python 2 in conda-forge since [it has been deprecated]( https://github.com/conda-forge/cfep/blob/51d6f68a7960ec7aada6641a72642a74c966eeda/cfep-15.md ). Please consider moving to Python 3.

Closing this issue.
