### ISSUE TITLE
gcc_linux-64 is no longer compatible with python 2.7.15

### ISSUE THREAD

**Issue by digi691** [conda-forge/python-feedstock#203]
Issue:

When installing gcc_linux-64 the package sets the environment variable `_CONDA_PYTHON_SYSCONFIGDATA_NAME` to `_sysconfigdata_x86_64_conda_cos6_linux_gnu` which is incorrect for the current conda-forge python=2.7.15=h33da82c_1.  This wasn't a problem until this commit https://github.com/conda-forge/python-feedstock/commit/a055a47bee8dd840c538eb3579978a9603eaa12d which backported support for `_CONDA_PYTHON_SYSCONFIGDATA_NAME`.  Either this patch should be reverted or the build should be changed to use FINAL_CONDA_PYTHON_SYSCONFIGDATA_NAME of `_sysconfigdata_x86_64_conda_cos6_linux_gnu`.

I found this issue during one of my own conda builds as it generated the following error:

`ImportError: No module named _sysconfigdata_x86_64_conda_cos6_linux_gnu`

As conda-forge's python 2.7 builds only provide `_sysconfigdata` and as stated previously, gcc_linux-64 hard sets `_CONDA_PYTHON_SYSCONFIGDATA_NAME` unless previously defined.

Workaround:
I unset `_CONDA_PYTHON_SYSCONFIGDATA_NAME` in my build.sh

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/cdigiovanni/.local/share/miniconda3/envs/python_2.7_test_2:
#
# Name                    Version                   Build  Channel
binutils_impl_linux-64    2.31.1               h6176602_1    defaults
binutils_linux-64         2.31.1               h6176602_3    defaults
ca-certificates           2018.8.24            ha4d7672_0    conda-forge
certifi                   2018.8.24             py27_1001    conda-forge
gcc_impl_linux-64         7.3.0                habb00fd_1    defaults
gcc_linux-64              7.3.0                h553295d_3    defaults
libffi                    3.2.1                hfc679d8_5    conda-forge
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
ncurses                   6.1                  hfc679d8_1    conda-forge
openssl                   1.0.2p               h470a237_0    conda-forge
pip                       18.0                  py27_1001    conda-forge
python                    2.7.15               h33da82c_1    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
setuptools                40.4.3                   py27_0    conda-forge
sqlite                    3.25.2               hb1c47c0_0    conda-forge
tk                        8.6.8                ha92aebf_0    conda-forge
wheel                     0.32.0                py27_1000    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : python_2.7_test_2
    active env location : /home/*.local/share/miniconda3/envs/python_2.7_test_2
            shell level : 2
       user config file : /home/*/.condarc
 populated config files : /home/*/.local/share/miniconda3/.condarc
          conda version : 4.5.11
    conda-build version : 3.10.6
         python version : 3.6.6.final.0
       base environment : /home/*/.local/share/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/cvxgrp/linux-64
                          https://conda.anaconda.org/cvxgrp/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch

          package cache : /home/*/.local/share/miniconda3/pkgs
                          /home/*/.conda/pkgs
       envs directories : /home/*/.local/share/miniconda3/envs
                          /home/*.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.6 Linux/4.15.15-1-ARCH arch/rolling glibc/2.26
                UID:GID : *:*
             netrc file : *
           offline mode : False

```
</details>

**Comment by jjhelmus** [comment]
conda-forge is currently maintaining two parallel sets of Python packages.  On the linux-64 platform, one set of packages uses the system compilers and the other which uses a newer gcc toolchain provided by conda packages.  

The [patch that causes this issue](https://github.com/conda-forge/python-feedstock/blob/2.7/recipe/0001-backport-Python-3.6-_PYTHON_SYSCONFIGDATA_NAME.patch) is required for the python packages compiled with the newer gcc toolchain but is not needed for the version which uses the system compilers and I believe should be removed.

**Comment by marscher** [comment]
So in the meantime we can not use the compiler to build packages against conda-forge anymore, but use the system provided toolchain?

**Comment by marscher** [comment]
so this cures the current build issues:
```
conda-build recipe -c conda-forge/label/gcc7
```

Thanks for sorting this out @jjhelmus. Just out of curiosity, why is it still working with the main cf channel on Python 3.5 and 3.6? Are these builds not patched with sysconfig?

**Comment by mingwandroid** [comment]
conda-forge and AD don't do Python 3.5 anymore. We support sysconfig_data in our latest build, conda-forge do not AFAIK.

**Comment by jjhelmus** [comment]
> Just out of curiosity, why is it still working with the main cf channel on Python 3.5 and 3.6?

There have been no builds of Python 3.5 since the switch to building the two variants and the 3.6 build was labeled as broken as it was causing issues.  In both cases you will be getting "older" packages that were created before the sysconfig patch.

**Comment by marscher** [comment]
I think this has been solved by rerendering the feedstock / installing from gcc7 label.
