### ISSUE TITLE
specify compiler in sysconfig

### ISSUE THREAD

**Issue by minrk** [conda-forge/python-feedstock#204]
Prompted by https://github.com/conda-forge/mpich-feedstock/issues/25, there's a question about what compiler commands should be the default for extensions in Python's sysconfig now that we are using the new conda compilers. There's a general question for conda packages built with new compilers that bundle records of commands that should be used to build downstream packages, especially when compilation is commonly done in user envs, not on CI infrastructure (as is the case for Python extensions).

The general question: how much should the default compiler commands map to the exact compiler used?

Right now, I believe the conda Python package forces sysconfig to use `'gcc'` as the default compiler/linker command for packages, regardless of the command used to compile Python itself (even on mac, apparently due to weird Python special-casing). Notably, the system clang on mac exports a `gcc` alias, but the conda clang does not. As far as I have followed the discussions, this is mainly an issue for C++ ABI, and thus not a major issue for Python, which I think uses only C.

The relevant points, I think:

- CPython is a C library, not a C++ library
- C libraries are mostly insensitive
- C++ libraries *are* sensitive to compilers
- Python does not depend on compilers, so the compilers are not generally available, but system compilers often are
- C extensions built with system compilers *do* generally work with Python built with newer conda compilers (I've tested the public wheels of pyzmq, numpy, scipy with new python3.7 package on linux, mac, for instance)
- there are several possible answers to the compiler string:
  - `$arch-$host-cc` (the default name of CC from build tools, fails unless conda compilers are present)
  - system-dependent "public" name `gcc` or `clang` (will find system compilers, but will use conda compilers *if present*)
  - `gcc` (current behavior, only finds system compilers on mac, not conda compilers)
  - include the env prefix, to ensure that compilers in the env are used unless explicitly overridden (fails without conda compilers)

I'm not sure what the right answers are, and it could be to leave it as 'gcc' for "just do what Python.org does" reasons, but I figured this should be open to make an informed decision on the matter. It may be that the decision should be different for C and C++, for instance, since C is much less sensitive to which compiler a given library has been built with, but C++ can have ABI issues.

One thing I've struggled with are actual failing cases. While C++ ABI compatibility has been discussed a lot, I've actually never seen an example or test case where the ABI compatibility comes up. If someone could produce an example with packages built using different compilers where things actually don't work, I think that would be super helpful for making an informed decision.

**Comment by jjhelmus** [comment]
conda-forge/conda-forge.github.io#616 gives some details on the C++ ABI compatibility issue and provides an example where this causes issues when mixing the two version of the `libprotobuf` library with `mosh`.

**Comment by isuruf** [comment]
Since most OSes have moved on to gcc 5+, this is not relevant now
