### ISSUE TITLE
UCS2 used on macOS Python 2.7 builds

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/python-feedstock#224]
Why is it for Python 2.7 we are using UCS2 for [macOS new compiler builds]( https://github.com/conda-forge/python-feedstock/blob/e3630fb3a3e5b9e89063624eae01b212cb8e2a36/recipe/gcc_build.sh#L69 ) and [old compiler builds]( https://github.com/conda-forge/python-feedstock/blob/e3630fb3a3e5b9e89063624eae01b212cb8e2a36/recipe/toolchain_build.sh#L30 ). AFAICT all of our other builds (including macOS for Python 3 versions) are using UCS4.

**Comment by jjhelmus** [comment]
The macOS ecosystem expects a narrow (UCS2) build of Python 2.7. Homebrew, MacPorts, the Apple Python 2.7 and the Python from python.org are all narrow builds.  Having conda provide a wide (UCS4) build would be unusual and likely cause compatibility issues.  

One big issue with a wide build would be that the vast majority of binary wheels on PyPI would be incompatible.  Most projects only provide macosx 2.7 wheels for the narrow ABI, (UCS2) which use the `cp27-cp27m` ABI tag. Very few, I know of none, provide wheels for the wide ABI, `cp27-cp27mu`.

**Comment by jakirkham** [comment]
Thanks for the added insight. That's what I was looking for.

Indeed this is the [same reason that Homebrew stuck with UCS2]( https://github.com/Homebrew/legacy-homebrew/pull/32368#issuecomment-56260783 ).

Just looking at NumPy's wheels for macOS with 1.15.4 confirms there is no `cp27-cp27mu` builds for macOS. Imagine that becomes a blocker for many other wheels as well.

While there is no technical limitation to providing a UCS4 macOS Python 2.7 build AFAICT, it does appear this would be an unusual build of Python and would not mesh well with the ecosystem.

Given macOS Python 3 builds have UCS4 support, Python 2.7 has roughly a year before its EOL, and the issues already noted with compatibility, it makes sense to close this as won't fix and simply encourage users in need of UCS4 on macOS to migrate to Python 3 instead.
