### ISSUE TITLE
Python 3.8.0 in the prerelease label

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/python-feedstock#254]
[Copied essentially verbatim from #177, @jjhelmus]

It would be great to provide Python 3.8.0 package in the [prerelease label](https://anaconda.org/conda-forge/python/files?channel=prerelease). I see that this channel includes everything from `3.6a3`-`3.6rc1`, but has nothing for 3.7. I'm opening this early so we can make sure 3.8 doesn't suffer the same fate. ;-)

For numpy/pandas etc. it would be good to be able to test this as early as possible. 

[PEP 569](https://www.python.org/dev/peps/pep-0569/) has the release schedule for the new version:

Version | Expected date
---------|-----------------------------
3.8.0 alpha 3| Monday, 2019-03-25
3.8.0 alpha 4| Monday, 2019-04-29
3.8.0 beta 1| Monday, 2019-05-27 (No new features beyond this point.)
3.8.0 beta 2| Monday, 2019-06-24
3.8.0 beta 3| Monday, 2019-07-29
3.8.0 beta 4| Monday, 2019-08-26
3.8.0 candidate 1| Monday, 2019-09-30
3.8.0 candidate 2| Monday, 2019-10-07 (if necessary)
3.8.0 final| Monday, 2019-10-21

**Comment by h-vetinari** [comment]
@jjhelmus @ocefpaf @isuruf 
Can I ask for a response to this please? :)
Is it something that's realistic?

**Comment by ocefpaf** [comment]
> Is it something that's realistic?

Not sure what you mean by realistic? Do you want to send a PR for 3.8 to the rc channel? If so, please do!

**Comment by h-vetinari** [comment]
> @ocefpaf: Not sure what you mean by realistic? Do you want to send a PR for 3.8 to the rc channel? If so, please do!

I haven't worked with conda recipes before. If you can point me to something I can work off of (for pre-release work), I'll try to have a look!

**Comment by jakirkham** [comment]
Sure, maybe you can try some variation of this commit ( https://github.com/conda-forge/python-feedstock/pull/253/commits/40fbebb64f2be759d1706d70cbdabefec5b74eda ) to start a new PR. IOW bump the version and update checksum. There may be more work that follows, but that would be a good first step.

**Comment by jjhelmus** [comment]
closed by #258

**Comment by h-vetinari** [comment]
@jjhelmus 
Thanks a lot for seeing this through (I barely did anything)!

This issue also covers the betas/rcs, but I'm guessing the those will be much easier now that we got something that passes the build, so probably fine to leave this closed.

**Comment by jjhelmus** [comment]
Yes future alpha, betas and rc release should be easier now that one of these releases is available on conda-forge.  alpha 4 is schedule for release soon.  There are two small fixes I want to get into the recipe when this is released.

**Comment by cdeil** [comment]
It's out: https://docs.python.org/3/whatsnew/3.8.html

Is there an issue one can watch or timescale when Python 3.8 becomes available?

**Comment by jjhelmus** [comment]
> Is there an issue one can watch

#274

**Comment by barispiero** [comment]
You can update your python version to 3.8 in conda using the command

conda install -c anaconda python=3.8
as per https://anaconda.org/anaconda/python. Though not all packages support 3.8 yet, running

conda update --all
may resolve some dependency failures. You can also create a new environment called py38 using this command

conda create -n py38 python=3.8
Edit – note that the conda install option will potentially take a while to solve the environment, and if you try to abort this midway through you will lose your Python installation (usually this means it will resort to non-conda pre-installed system Python installation).

Full Source code At [Here](https://icetutor.com/question/upgrade-to-python-3-8-using-conda/)
