### ISSUE TITLE
Add conda path directories to library search order once

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/python-feedstock#280]
The patches in #279 (`0019`) and #274 (`0020`) add the "conda paths" to the DLL search order each time a library is loaded on Windows.  This is inefficient, these directories only need to be added to the search order once.  Additionally the functionality in patch `0020` in #274 in helpful when debugging and is more efficient.  These two patches should be combined.

**Comment by isuruf** [comment]
It's added only once now in 3.9 and 3.10
