### ISSUE TITLE
Add a patch for https://bugs.python.org/issue37916

### ISSUE THREAD

**Issue by isuruf** [conda-forge/python-feedstock#281]
With OSX python 3.8 being an lto build, this issue pops up now. Here's a patch https://github.com/isuruf/cpython/commit/94cecb5a61e6f071c39602ded60e32626f54f0f8.patch

**Comment by isuruf** [comment]
@conda-forge/python, can someone with OSX access try the above patch (you can edit sysconfig.py in your installation and don't need to rebuild python) and try building numpy without https://github.com/conda-forge/numpy-feedstock/blob/c7cf486c7f452935d079e41f180e4742a0f7baa9/recipe/build.sh#L5-L7 ?

**Comment by chrisburr** [comment]
> @conda-forge/python, can someone with OSX access try the above patch (you can edit sysconfig.py in your installation and don't need to rebuild python) and try building numpy without https://github.com/conda-forge/numpy-feedstock/blob/c7cf486c7f452935d079e41f180e4742a0f7baa9/recipe/build.sh#L5-L7 ?

It works 👍
