### ISSUE TITLE
Remove -dead_strip_dylibs from _sysconfigdata_x86_64_apple_darwin13_4_0

### ISSUE THREAD

**Issue by isuruf** [conda-forge/python-feedstock#289]
`-dead_strip_dylibs` is in `LDFLAGS` env variable, so it's not necessary to have this baked into python. Removing this from here makes it easy to remove this flag when necessary. (Removing the flag from `LDFLAGS` env variable is enough). Otherwise a user has to remove the flag by removing it from `LDFLAGS` env variable and setting `LDSHARED` to the python's `LDSHARED` value minus the `-dead_strip_dylibs` flag.

cc @oleksandr-pavlyk, @jjhelmus

**Comment by jakirkham** [comment]
Was it added intentionally here? If so, what was the reason for it?

Also cc-ing @mingwandroid

**Comment by mingwandroid** [comment]
Sure, we add it to all LDFLAGs on macOS. We want to strip unused libs. This 'deliberate dynamic' behavior is the less common case, whereas the more common case will be things getting linked to by mistake.

But I don't care either way if I'm being honest with you.

If some thinks it appropriate that this should be somehow 'handled' in the ecosystem, for example via conda-build metadata (`build/allow_unused_dsos` for example), then I am all ears and would not mind hacking on that as a feature.

But for now, I'd rather say no, the rarer corner cases should be handled explicitly for now instead of making things worse in other cases.

**Comment by mingwandroid** [comment]
> Otherwise a user has to remove the flag by removing it from LDFLAGS env variable and setting LDSHARED to the python's LDSHARED value minus the -dead_strip_dylibs flag

This is preferable to us linking to many DSOs we do not need to link to across our ecosystem.

**Comment by jjhelmus** [comment]
I believe that including `LDSHARED="${LDFLAGS//-Wl,-dead_strip_dylibs}"` in the build script will make the necessary modification needed for packages which cannot use `-dead_strip_dylibs`.

**Comment by mingwandroid** [comment]
It could work but its not future proof (python is free to augment LDFLAGS). I would rather we added a way for sysconfig to remove unwanted flags in these cornercases.

I see no good reason not to use dladdr() for this kind of thing either.

**Comment by isuruf** [comment]
But why do you need the duplication in `LDFLAGS` and python's `sysconfig`? It makes it hard for the user to override it because the user has to override both.

> I believe that including LDSHARED="${LDFLAGS//-Wl,-dead_strip_dylibs}" in the build script will make the necessary modification needed for packages which cannot use -dead_strip_dylibs.

I don' think that works. LDSHARED has other flags to make a shared library that is not in LDFLAGS.

**Comment by mingwandroid** [comment]
I propose we patch python (again, sorry), so we can pass LDSHARED_REMOVE, much like the MSYS2_PATH/ENV_EXCL stuff. Thoughts?

**Comment by isuruf** [comment]
I hate patching a software for something like this. I'm still not clear on why we need the duplication of `-dead_strip_dylibs` in both `LDFLAGS` env var and in python's `sysconfig`.

**Comment by mingwandroid** [comment]
I've done my best to explain. Please help me with that.

Various build systems and implementations of them ask distutils for the appropriate flags to link python extension modules. They do that by asking for the value of LDSHARED. It is better if we strip unneeded DSOs in the general case.

Python ignores LDFLAGS when people query distutils directly like this.

**Comment by jjhelmus** [comment]
> I don' think that works. LDSHARED has other flags to make a shared library that is not in LDFLAGS.

Yes, that does not work.  The following seems to be correct:

```
LDSHARED=`python -c "import sysconfig; print(sysconfig.get_config_var('LDSHARED'))"`
LDSHARED="${LDSHARED//-Wl,-dead_strip_dylibs/}"
```

Also, for reference if you need to obtain these flags from an environment that does not have `clang_osx-64` installed the ` _CONDA_PYTHON_SYSCONFIGDATA_NAME` environment variable can set set, for example:

```
(base) ~$ python -c "import sysconfig; print(sysconfig.get_config_var('LDSHARED'))"
gcc -bundle -undefined dynamic_lookup -L/Users/jhelmus/conda/lib  -arch x86_64 -L/Users/jhelmus/conda/lib  -arch x86_64
(base) ~$ _CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_apple_darwin13_4_0 python -c "import sysconfig; print(sysconfig.get_config_var('LDSHARED'))"
x86_64-apple-darwin13.4.0-clang -bundle -undefined dynamic_lookup -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/jhelmus/conda/lib -L/Users/jhelmus/conda/lib -flto -Wl,-export_dynamic -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/jhelmus/conda/lib -L/Users/jhelmus/conda/lib
```

**Comment by jschueller** [comment]
some examples of recipes where you have to filter out -dead_strip_dylibs:
https://github.com/conda-forge/paraview-feedstock/issues/107
https://github.com/AnacondaRecipes/intel_repack-feedstock/issues/8

for paraview I added:
```
export LDFLAGS=`echo "${LDFLAGS}" | sed "s|-Wl,-dead_strip_dylibs||g"`
```

**Comment by isuruf** [comment]
Removed now in 3.10 and 3.9
