### ISSUE TITLE
System ranlib is used instead of conda-forge::compilers on the conda-forge infrastructure on macOS with Pyhon 3.7

### ISSUE THREAD

**Issue by ogrisel** [conda-forge/python-feedstock#302]
This problem is specific to the conda-forge CI infrastructure and cannot be reproduced locally. It was discovered on this scikit-learn-feedstock PR:

https://github.com/conda-forge/scikit-learn-feedstock/pull/115#issuecomment-570254995

@scopatz [told me](https://github.com/conda-forge/compilers-feedstock/issues/19#issuecomment-570943642) to report this issue here.

**Comment by isuruf** [comment]
https://github.com/conda-forge/python-feedstock/blob/master/recipe/patches/0020-Use-ranlib-from-env-if-env-variable-is-set.patch needs to be backported to 3.7 branch

**Comment by isuruf** [comment]
@ogrisel, can you send a PR?

**Comment by jjhelmus** [comment]
Backported patch to 3.7 branch in #304

**Comment by ogrisel** [comment]
Thanks very much!

**Comment by jjhelmus** [comment]
closed via #304
