### ISSUE TITLE
python_abi dependency getting injected into noarch packages

### ISSUE THREAD

**Issue by TimoRoth** [conda-forge/python-feedstock#353]
I'm not 100% sure where to report this, but this repo seems to most appropriate to me.
We are building a few Conda-Packages, which base on conda-forge packages.
You can see those packages here: https://github.com/OGGM/OGGM-Anaconda/tree/master/build

All of them are "build: noarch: python" packages. They are pure python and do not contain any binary code.
However, after building them, all of them get dependency on "python_abi 3.7.* *_cp37m" (or whatever python version they were built with) injected into their index.json. Thus breaking the package on all but the python version they happened to have been build on.

I don't see any reason why that dependency should be in there. How do I get rid of it?
I'd really like to avoid having to split up my pure python packages into identical but python version specific ones.

**Comment by isuruf** [comment]
Please use a newer conda-build version. (Ideally from conda-forge)
