### ISSUE TITLE
The `ld` symlink in `compiler_compat` seemingly points to the wrong binary in python=3.8.3

### ISSUE THREAD

**Issue by igozali** [conda-forge/python-feedstock#355]
Issue: I have a conda environment with only 1 package: `python=3.8.3`. My `env.yaml` is as follows:
```yaml
name: igozali-test
prefix: /root/envs/igozali-test
channels:
- conda-forge
dependencies:
- python=3.8
```

After I've created the environment and installed the only package using the `env.yaml`, I looked inside the prefix directory, and found that the symlink `compiler_compat/ld` seems to be pointing to `../bin/x86_64-conda-linux-gnu-ld`, which doesn't exist. Rather, it seems that it should be pointing to `../bin/x86_64-conda_cos6-linux-gnu-ld`
```
(igozali-test) root@839e10e822ea:~# cd ~/anaconda3/envs/igozali-test/compiler_compat/
(igozali-test) root@839e10e822ea:~/anaconda3/envs/igozali-test/compiler_compat# ls -alh
total 12K
drwxr-xr-x  2 root root 4.0K Jul  9 06:23 .
drwxr-xr-x 10 root root 4.0K Jul  9 06:23 ..
-rw-rw-r--  2 root root  173 Jun  1 17:57 README
lrwxrwxrwx  1 root root   32 Jul  9 06:23 ld -> ../bin/x86_64-conda-linux-gnu-ld
(igozali-test) root@839e10e822ea:~/anaconda3/envs/igozali-test/compiler_compat# ls ../bin/x86_64-conda-linux-gnu-ld
ls: cannot access '../bin/x86_64-conda-linux-gnu-ld': No such file or directory
(igozali-test) root@839e10e822ea:~/anaconda3/envs/igozali-test/compiler_compat# ls ../bin/x86_64-conda_cos6-linux-gnu-ld
../bin/x86_64-conda_cos6-linux-gnu-ld
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list --show-channel-urls
# packages in environment at /root/anaconda3/envs/igozali-test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py38h32f6830_0    conda-forge
ld_impl_linux-64          2.34                 h53a641e_5    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
pip                       20.1.1                     py_1    conda-forge
python                    3.8.3           cpython_he5300dc_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
setuptools                49.1.0           py38h32f6830_0    conda-forge
sqlite                    3.32.3               hcee41ef_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xz                        5.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : igozali-test
    active env location : /root/anaconda3/envs/igozali-test
            shell level : 2
       user config file : /root/.condarc
 populated config files :
          conda version : 4.7.10
    conda-build version : 3.18.8
         python version : 3.7.3.final.0
       virtual packages :
       base environment : /root/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /root/anaconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /root/anaconda3/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.10 requests/2.22.0 CPython/3.7.3 Linux/4.19.76-linuxkit ubuntu/18.04.4 glibc/2.27
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```
</details>

**Comment by jjhelmus** [comment]
The target of the ld [symlink is generated from $HOST variable](https://github.com/conda-forge/python-feedstock/blob/162be594485664249bf04ecde1b789d1e0d74817/recipe/build.sh#L399) which is set by the activation script in binutils.  In conda-forge/binutils-feedstock#25 `cos6` was remove from HOST.  

I think changing the symlink target to use $OLD_HOST if set should be sufficient but would appreciate input from other @conda-forge/binutils maintains.  

The `sysconfig_...` files [also use $HOST](https://github.com/conda-forge/python-feedstock/blob/162be594485664249bf04ecde1b789d1e0d74817/recipe/build.sh#L362-L395) to derive names and may require a change.

**Comment by isuruf** [comment]
cc @beckermr

**Comment by beckermr** [comment]
I thought we inserted extra symlinks to the old names.

**Comment by beckermr** [comment]
I’ll need to investigate a bit tonight.

**Comment by igozali** [comment]
Just to add a bit more info, if I remove that symlink and repoint it to the correct binary (the one with `cos` in the name), my Python extension build does work in the end.

**Comment by beckermr** [comment]
Is the env output above correct? The build of ld you are using is from the 2.34 branch of the binutils feedstock and that branch only uses the old sysroot names.

**Comment by igozali** [comment]
I tested the above in Docker, let me double check real quick.

**Comment by beckermr** [comment]
I downloaded this package and don't see the bad symlink:

https://anaconda.org/conda-forge/ld_impl_linux-64/2.34/download/linux-64/ld_impl_linux-64-2.34-h53a641e_5.tar.bz2

**Comment by igozali** [comment]
I think the symlink is from the python side?

**Comment by beckermr** [comment]
ah - we need to rebuild python 3.8.3

**Comment by beckermr** [comment]
We could/ should also add extra symlinks to the ld package. Thoughts @isuruf?

**Comment by isuruf** [comment]
I don't know where the build number 5 came from. build number 4 has the correct symlinks.

**Comment by beckermr** [comment]
The 2,34 branch of binutils

**Comment by beckermr** [comment]
PR here: https://github.com/conda-forge/binutils-feedstock/pull/34

**Comment by igozali** [comment]
Thanks very much for your work on this - really appreciate it. I saw that the PR has been merged; does that mean I can now just install `python=3.8.3` through `conda` as normal now, or do I have to wait for the Python package to be rebuilt as well? Pardon my unfamiliarity with the conda build system :)

**Comment by beckermr** [comment]
It should work without rebuilding python. If it does not, let us know.

**Comment by igozali** [comment]
Tested, works indeed, thank you! Let me close this issue then.

**Comment by jjhelmus** [comment]
@isuruf @beckermr The new symlink in the binutils fixes the immediate issue but python packages with the `x86_64-conda-linux-gnu-ld` symlink will not work with older `ld_impl_linux-64` packages or those in `defaults`

**Comment by beckermr** [comment]
Ugh. @isuruf seemed to indicate to me that we should not be allowing binutils to downgrade versions anyways which also impacts this discussion. However, I cannot find a link to the compatibility ranges for it via google. 

@isuruf can you comment here?

**Comment by beckermr** [comment]
> those in defaults

I had hoped strict channel priority would avoid this issue

> not work with older ld_impl_linux-64 packages 

I thought the solver would always pull the latest build if possible. Do you have an example solve where it is not?

I guess we could insert a sysroot mutex in places, but this seems pretty heavy-handed.

**Comment by jjhelmus** [comment]
conda will pull in the latest version by default and strict channel priority will prevent packages from `defaults` from being installed.  My point was that changing `HOST` breaks backwards compatibility and compatibility with `defaults`.  Both are okay if that is the intention it just isn't the most user-friendly change in my opinion.

**Comment by beckermr** [comment]
> conda will pull in the latest version by default and strict channel priority will prevent packages from defaults from being installed. My point was that changing HOST breaks backwards compatibility and compatibility with defaults. Both are okay if that is the intention it just isn't the most user-friendly change in my opinion.

Right. We are aware of these issues and have tried our best to put in patches in various spots to prevent broken envs. This is definitely an edge case where the patches are not yet sufficient.

**Comment by jjhelmus** [comment]
@beckermr @isuruf Would you be opposed to the compiler_compat/ld symlink pointing to `x86_64-conda_cos6-linux-gnu-ld` even in cases where this does not match $HOST?

**Comment by beckermr** [comment]
This would have to be arch dependent since it is cos7 in places, but I don't see an issue with it. As of now we plan to keep these extra links going forward even when we do bump to the new sysroot-based versions of binutils on master. 

I cannot speak for @isuruf though so he should comment too.

**Comment by isuruf** [comment]
> Would you be opposed to the compiler_compat/ld symlink pointing to x86_64-conda_cos6-linux-gnu-ld even in cases where this does not match $HOST?

I'm `-0` on this. We'll never be able to switch to `-conda-` since even new python packages will be dependent on `-conda_cos6-`. How about adding a constraint of `ld_impl_linux-64>=2.34`?

**Comment by jjhelmus** [comment]
> How about adding a constraint of `ld_impl_linux-64>=2.34`?

That sounds good to me.  Python 3.8.4 is out so this change can be incorporated into that version.  The existing packages could be hotfixed to add this bound if there are concerns.  I'm fine waiting for a report of the error for the hotfix.
