### ISSUE TITLE
Revert #367

### ISSUE THREAD

**Issue by isuruf** [conda-forge/python-feedstock#380]
The whole `build` section in the top level package does not apply to the outputs. So, run_exports are wrong now.

cc @xhochy

**Comment by isuruf** [comment]
@xhochy, do you have time to fix this? If not, I'll revert

**Comment by xhochy** [comment]
I allocated some time to deal with possible fallout as this is an important feedstock, will now look into it.

**Comment by isuruf** [comment]
Thanks @xhochy. I managed to fix it in https://github.com/conda-forge/python-feedstock/pull/376, but it's with other changes.

**Comment by xhochy** [comment]
Pushed these changes to #379
