### ISSUE TITLE
Windows scripts slightly wrong as of 3.8.5 build 3, leading to packages with unwanted Python files

### ISSUE THREAD

**Issue by pkgw** [conda-forge/python-feedstock#384]
It was reported in conda-forge/tectonic-feedstock#21 that the latest Windows package of that project contains some miscellaneous Python-related files such as `Scripts/2to3.exe`. It seems that this is being caused by a change that went in to the Windows builds of Python between builds 2 and 3 of 3.8.5:

```
$ tar tjf python-3.8.5-h5fd99cc_2_cpython.tar.bz2 |grep Scripts/
Scripts/pydoc-script.py
Scripts/idle-script.py
Scripts/2to3-script.py
Scripts/idle.exe
Scripts/2to3.exe
Scripts/pydoc.exe

# ^^^ earlier builds also have -script.py and .exe files

$ tar tjf python-3.8.5-h60c2a47_3_cpython.tar.bz2 |grep Scripts/
Scripts/pydoc
Scripts/idle
Scripts/2to3

# ^^^ the later builds also have extension-less files only
```

When building Tectonic on Windows with a Python build > 3.8.5_*_3, something is triggered right as the package is being tested that causes the `-script.py` and `.exe` versions of these scripts to be populated in the `Scripts/` directory. This then causes those files to be added to the Windows package, [for instance](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=200083&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=1329):

```
INFO:conda_build.build:Packaging tectonic
Adjusting unix-style #! script 2to3, and adding a .bat file for it
INFO conda_build.build:build(2074): Packaging tectonic
INFO:conda_build.build:Packaging tectonic-0.1.12-h87e793b_2
INFO conda_build.build:bundle_conda(1388): Packaging tectonic-0.1.12-h87e793b_2
Adjusting unix-style #! script idle, and adding a .bat file for it
Adjusting unix-style #! script pydoc, and adding a .bat file for it
```

I've monitored `Scripts/` as the build proceeds and can confirm that the files are only created *after* the build completes.

If I build with a 3.7 version of Python, those files already exist in the Python package and so the Tectonic package comes out with the right complement of files.

Either something needs to be changed in the Python recipe to get packages back how they used to be, or I think something in conda-build needs updating to not trigger the creation of these extra files.

**Comment by isuruf** [comment]
cc @xhochy. This seems to be because of having multiple outputs. xref: https://github.com/conda/conda-build/blob/375e1618058504e004117fe65736125eea43fcd2/conda_build/build.py#L2116-L2122

**Comment by isuruf** [comment]
@pkgw, can you send a PR to https://github.com/conda-forge/admin-requests to mark the builds after 3 as broken?

**Comment by xhochy** [comment]
@isuruf As far as I understand, the issue is that `conda_build.windows.fix_staged_scripts` is not called for the scripts in outputs?

**Comment by xhochy** [comment]
Opened a mark-broken PR: https://github.com/conda-forge/admin-requests/pull/116

**Comment by pkgw** [comment]
Oops, it turned out that there are two Windows `3.8.5_*_2` builds, one of which is also broken — another mark-broken PR added in conda-forge/admin-requests#117.

**Comment by isuruf** [comment]
> As far as I understand, the issue is that conda_build.windows.fix_staged_scripts is not called for the scripts in outputs?

Yes

**Comment by xhochy** [comment]
I made a workaround for this in https://github.com/conda-forge/python-feedstock/pull/385, I'll have a look for a proper fix in conda-build later.
