### ISSUE TITLE
Maintaining many versions

### ISSUE THREAD

**Issue by pelson** [conda-forge/python-feedstock#41]
We need to be careful to distinguish between versions we want to support, and versions that we want to have built in the past.

The history has been really interesting to see Python 1 grow, but we don't need to *maintain* recipes for it. Instead, I propose we build them (i.e. merge), tag the commit that we used, and then delete the branch. Ideally, all of this would be done with a common (read: linear) git history, so that we can diff the build between two versions.

Thoughts @jjhelmus?

**Comment by jjhelmus** [comment]
I'm not following the workflow here @pelson.  Doesn't every commit belong to at least one branch?  If we delete the branches with Python 1.X builds wouldn't the commits be deleted with them?

Is there a reason not to have branches for all of the various releases?  I can imagine having all of the branches might clutter the GitHub UI a bit and might suggest that we are supporting these historic versions but we could prefix the branch names with `historic_` or something similar to move them to the end of the list.

I would be fine if we had a single `1.x` branch where all of these commits where made linearly and tagged, or even a `historic` or `un-maintained` branch for all of these as I'm hoping to make 2.0, 2.1, ... 2.5 builds to complete the series.

**Comment by pelson** [comment]
> Is there a reason not to have branches for all of the various releases?

Each branch would get 1 rerender PR and 1 pinning PR whenever anything changes. The burden of maintenance and the additional (though relatively limited) burden on the CI are my main motivations.

I'd like to get to a point where we have the history of each of these changes in the repo, but where we aren't maintaining one branch per release.

**Comment by jjhelmus** [comment]
Talking at SciPy it sounds like a single `historic` branch with tagged commits for Python 1.X, and older 2.X releases is the best solution.  I created PR #44 to start this branch.

**Comment by jakirkham** [comment]
SGTM

**Comment by jjhelmus** [comment]
Python 1.0.1, 1.2, 1.3, 1.5.2, 1.6 and 2.0 have been added to the `historic` branch and tagged.  Packages for Linux and OS X for these Python versions are available on the `conda-forge` channel.

If any other older 2.x packages are built they should be added to the `historic`branch and tagged using this method.

Closing issue.
