### ISSUE TITLE
Update to 3.7.9 and use latest macOS SDK to fix Qt crash

### ISSUE THREAD

**Issue by rggjan** [conda-forge/python-feedstock#424]
Updating python to 3.7.9 and applying the changes here:
https://github.com/conda-forge/python-feedstock/pull/412

Would fix this isse:
https://github.com/conda-forge/pyside2-feedstock/issues/46

*and* Qt crashing on macOS Big Sur...

**Comment by isuruf** [comment]
https://github.com/conda-forge/python-feedstock/pull/462 should fix this issue for python 3.8 and 3.9 is already fixed. @rggjan, are you still using python 3.7?

**Comment by rggjan** [comment]
Good to know 3.8 is also fixed, though!

**Comment by isuruf** [comment]
Is this bug on Big Sur only or on 10.15 too?

**Comment by rggjan** [comment]
I think only Big Sur...

**Comment by rggjan** [comment]
(At least the crash...)

**Comment by mbargull** [comment]
FYI, gh-462 seemed to have caused some kind of regression in at least one case for 3.8: https://github.com/conda-forge/cctbx-base-feedstock/issues/22 (3.9 builds work fine, though).

**Comment by isuruf** [comment]
3.7 support is now dropped
