### ISSUE TITLE
Issues with Python 3.9.1 on Big Sur (Rosetta)

### ISSUE THREAD

**Issue by astrofrog** [conda-forge/python-feedstock#436]
If I use conda on Big Sur with Rosetta (to use x86_64 binaries) I run into issues when trying to import vispy (as an example):

```
% conda create -n test44 -c conda-forge python=3.9 vispy
% conda activate test44
% python -c 'import vispy'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/tom/miniconda3/envs/test44/lib/python3.9/site-packages/vispy/__init__.py", line 30, in <module>
    from .util import config, set_log_level, keys, sys_info  # noqa
  File "/Users/tom/miniconda3/envs/test44/lib/python3.9/site-packages/vispy/util/__init__.py", line 14, in <module>
    from . import fonts       # noqa
  File "/Users/tom/miniconda3/envs/test44/lib/python3.9/site-packages/vispy/util/fonts/__init__.py", line 13, in <module>
    from ._triage import _load_glyph, list_fonts  # noqa, analysis:ignore
  File "/Users/tom/miniconda3/envs/test44/lib/python3.9/site-packages/vispy/util/fonts/_triage.py", line 14, in <module>
    from ._quartz import _load_glyph, _list_fonts
  File "/Users/tom/miniconda3/envs/test44/lib/python3.9/site-packages/vispy/util/fonts/_quartz.py", line 12, in <module>
    from ...ext.cocoapy import cf, ct, quartz, CFRange, CFSTR, CGGlyph, UniChar, \
  File "/Users/tom/miniconda3/envs/test44/lib/python3.9/site-packages/vispy/ext/cocoapy.py", line 1126, in <module>
    NSEventTrackingRunLoopMode = c_void_p.in_dll(
ValueError: dlsym(RTLD_DEFAULT, NSEventTrackingRunLoopMode): symbol not found
```

However if I build and install Python 3.9.1 and pip install vispy, I don't see this issue. The main difference is that the version built from source has a MACOSX_DEPLOYMENT_TARGET of 11 whereas the conda-forge Python executable was compiled with an older deployment target, though it might be that there is another root cause for this issue.

Output of ``conda info``:

<details>

```
% conda info

     active environment : test44
    active env location : /Users/tom/miniconda3/envs/test44
            shell level : 2
       user config file : /Users/tom/.condarc
 populated config files : 
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/tom/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/tom/miniconda3/pkgs
                          /Users/tom/.conda/pkgs
       envs directories : /Users/tom/miniconda3/envs
                          /Users/tom/.conda/envs
               platform : osx-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Darwin/20.1.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

</details>

**Comment by astrofrog** [comment]
This issue can also be demonstrated outside of conda - if I use the 'macOS 64-bit Intel installer' for Python 3.9.1, the error occurs, whereas if I use the universal2 installer it works fine (again I suspect the main difference that is relevant here is the deployment target)

**Comment by astrofrog** [comment]
And to make things more fun - things work fine with Python 3.9.0:

```
% conda create -n test45 -c conda-forge python=3.9.0 vispy
% conda activate test45
% python -c 'import vispy'
```

To be clear, this is not a vispy issue but a Python issue, since the problem is ``ctypes.util.find_library`` calls that are failing when they should work.

**Comment by isuruf** [comment]
Can you do `_ = ctypes.cdll.LoadLibrary(ctypes.util.find_library('AppKit'))` before importing `vispy`?

**Comment by astrofrog** [comment]
Also as another datapoint, things do *not* work with the 3.9.0 Python org installer. I'm not sure why the 3.9.0 conda-forge Python does work but not 3.9.1 - but if we know the differences between those builds that might help figure it out.

@isuruf - no change, and just for the record the find_library call returns ``None`` for AppKit:

```
>>> ctypes.cdll.LoadLibrary(ctypes.util.find_library('AppKit'))
<CDLL 'None', handle fffffffffffffffe at 0x1093224c0>
```

However this works fine with the 3.9.0 build from conda-forge:

```
>>> ctypes.cdll.LoadLibrary(ctypes.util.find_library('AppKit'))
<CDLL '/System/Library/Frameworks/AppKit.framework/AppKit', handle 7f80e3604280 at 0x7f80f825dc70>
```

**Comment by isuruf** [comment]
Try doing `ctypes.cdll.LoadLibrary('/System/Library/Frameworks/AppKit.framework/AppKit')`

**Comment by astrofrog** [comment]
@isuruf - that works:

```
>>> ctypes.cdll.LoadLibrary('/System/Library/Frameworks/AppKit.framework/AppKit')
<CDLL '/System/Library/Frameworks/AppKit.framework/AppKit', handle 7facc8f04290 at 0x10af147f0>
```

**Comment by isuruf** [comment]
After that, `import vispy` works?

**Comment by astrofrog** [comment]
No - but if I patch vispy to hard-code the absolute path to AppKit it then works.

**Comment by isuruf** [comment]
Ok, so it's not a packaging issue.

**Comment by marcelotduarte** [comment]
https://github.com/conda-forge/cx_freeze-feedstock/pull/24 fails
https://github.com/conda-forge/cx_freeze-feedstock/pull/25 ok fixing python 3.9.0 for macOS

**Comment by isuruf** [comment]
@marcelotduarte, can you create a new issue to remove `-Wl,-export_dynamic` in python 3.9 in macOS?

**Comment by isuruf** [comment]
@astrofrog, see https://github.com/python/cpython/pull/24324. PRs are welcome to patch the conda packages for 3.8 and 3.9.
