### ISSUE TITLE
sigsegv/sigbus on numba import, Apple M1

### ISSUE THREAD

**Issue by stuartarchibald** [conda-forge/python-feedstock#439]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

This information is from a [Numba](https://github.com/numba/numba) user (@stnatter) reporting it and debugging it with them on IRC.
Original conversation is here: https://gitter.im/numba/numba?at=600765c1410c2214400d8c2a
Originally reported ticket is here: https://github.com/numba/numba/issues/6650

Essentially, on an `osx-arm64` machine, picking up packages from `conda-forge`, the code:
```
import numba
```
causes `SIGSEGV` or `SIGBUS` when using `python 3.8.5-h05baefb_9_cpython`. Keeping everything else in the environment the same but moving to `python 3.8.6-h12cc5a1_4_cpython` and the same import works fine.

Thanks to @stnatter for helping to debug.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
python 3.8.5-h05baefb_9_cpython OR 3.8.6-h12cc5a1_4_cpython
numba= 0.52.0 py38h9b9bf68_0
llvmlite=0.35.0 py38h57246dd_1
llvmlite=0.35.0 py38h57246dd_1
```
</details>

**Comment by isuruf** [comment]
PRs welcome to https://github.com/conda-forge/admin-requests to mark the 3.8.5 builds as broken. I didn't expect anyone to use the older 3.8.5 builds.

**Comment by bollwyvl** [comment]
Maybe related? https://github.com/ipython/ipython/issues/12803#issuecomment-771285668

**Comment by stnatter** [comment]
> Maybe related? [ipython/ipython#12803 (comment)](https://github.com/ipython/ipython/issues/12803#issuecomment-771285668)

Numba works fine for me on `Python=3.8.6`. Having the same problem with `matplotlib` using `iPython` as described there though.
