### ISSUE TITLE
Update to 3.9.5 and 3.8.10

### ISSUE THREAD

**Issue by isuruf** [conda-forge/python-feedstock#459]
They are out today.

**Comment by cgohlke** [comment]
Python 3.9.3 breaks the ABI. See https://bugs.python.org/issue43710 and https://github.com/python/cpython/pull/25160

**Comment by isuruf** [comment]
Thanks @cgohlke for the info

**Comment by isuruf** [comment]
3.9.4 has been released now which fixes the ABI.

**Comment by gatto** [comment]
If I could propose changing the title to

`Update to 3.9.5 and 3.8.10`
😀

**Comment by isuruf** [comment]
Sure. 3.9.4 is failing at https://github.com/conda-forge/python-feedstock/pull/460 where some patches fail to apply. I guess we'll have patch failures in 3.9.5 too
