### ISSUE TITLE
Do a 2.7.18 build?

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [conda-forge/python-feedstock#465]
2.7.18 is the final version from python.org

But conda-forge's last is 2.7.15

2.7.18 is in defaults, but that's a bit tricky, because if you create a conda environment with python2 as a requirement, and you have conda-forge as the highest priority channel, then you get 2.7.15

And it's not very clear how to get 2.7.18 other than asking for it directly:

conda install 2.7.18

Given that 2.7.18 is the final release, it's not too big a deal to pin the version in requirements, but it seems it would be nice if conda forge did supply the latest build be default.

Yeah, I know 2.7 is end of life -- but imagine there will be alot of us limping along running it for a while :-)

**Comment by jakirkham** [comment]
If someone wants to do that work, I'm sure that would be ok. Is this something that you are interested in doing?

**Comment by ChrisBarker-NOAA** [comment]
In  theory, I could do it. Though I see a lot of patches and all, so it may be out of my depth if a lot has changed since the last build :-(

**Comment by ChrisBarker-NOAA** [comment]
Also, we haven't had a build of 2.7 for a good while -- which means it was decided to not do it for the last few point releases. I"m wondering if there was a more compelling radon not to do it than "no one goy around to it".

**Comment by isuruf** [comment]
> I"m wondering if there was a more compelling radon not to do it than "no one got around to it".

Nope. That's almost always the reason for all of conda-forge issues.

**Comment by ChrisBarker-NOAA** [comment]
We've decided that it's not worth our effort to update this. It's a bit tricky to get the latest py2.7 with a conda-forge based environment, but it can be done, and hopefully py2 will die eventually :-)

**Comment by jason-s** [comment]
I would really like to see this reopened; I know that Python 2 is in an unsupported frozen state, but to me that has always been 2.7.18, which I can get from downloading from python.org or the Anaconda conda repo. But not here.

**Comment by jason-s** [comment]
Is there any way to sponsor such work? I can't afford it, and my employer probably wouldn't be willing to fund much, but maybe I could get them to pay something.

**Comment by jason-s** [comment]
Hmm, I can't even seem to install Python 2.7.15 (see #637)
