### ISSUE TITLE
Recent 3.7 backports break cryptography test suite

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/python-feedstock#518]
Unfortunately the story of #516, #517 in the [context](https://github.com/conda-forge/python-feedstock/issues/516#issuecomment-942220263) of openssl 3 vs. python 3.7 isn't over yet.

#517 introduced a hang in the cryptography test suite - though only on linux. I noticed this because https://github.com/conda-forge/cryptography-feedstock/pull/71 was opened before #517 was merged (and had passing CI), but now hangs after the merge.

To verify this hypothesis, I did another run using the [previous](https://github.com/conda-forge/cryptography-feedstock/pull/74/commits/be2824b0f37ece48c29b697fa734d492f4197538) python 3.7 build in https://github.com/conda-forge/cryptography-feedstock/pull/74, which passes the test suite.

Finally, to rule out that it had something to do with the cryptography update itself, I did the [same](https://github.com/conda-forge/cryptography-feedstock/pull/75/commits/731ba0257757364b3d7133d7fa4f3126ab350af0) in https://github.com/conda-forge/cryptography-feedstock/pull/75 for the previous cryptography version, and the CI passes there as well.

CC people involved in #516 / #517:  @akrherz @chrisburr @isuruf @chenghlee @jakirkham

**Comment by h-vetinari** [comment]
Note, the OpenSSL 3 migrator hasn't reached the cryptography-feedstock yet, so the hang appears with the widely deployed python 3.7 + OpenSSL 1.1.1.

**Comment by h-vetinari** [comment]
> is it possible to get a simple one-line test that reproduces this issue such that I could again whack-a-mole back-porting patches that maybe fix it?

Comparing the stalled test suite
```
tests/hazmat/backends/test_no_backend.py ..                              [  2%]
tests/hazmat/backends/test_openssl.py ..................sssssss......... [  4%]
....ss.............sssssss...                                            [  5%]
[no more output]
```
with the pypy37 job of the same run
```
tests/hazmat/backends/test_no_backend.py ..                              [  2%]
tests/hazmat/backends/test_openssl.py ..................sssssss......... [  4%]
....ss.............sssssss...                                            [  5%]
tests/hazmat/backends/test_openssl_memleak.py .................          [  5%]
tests/hazmat/bindings/test_openssl.py .........                          [  6%]
```

It seems pretty clear that the failure happens somewhere in [this](https://github.com/pyca/cryptography/blob/35.0.0/tests/hazmat/backends/test_openssl_memleak.py) test module.

You should be able to run just that with `pytest tests/hazmat/backends/test_openssl_memleak.py` - hope that's reduction enough to start?

**Comment by jakirkham** [comment]
@isuruf could you please clarify what your concern is with the suggestion above? If we discover that this only happens on an old OpenSSL we don't want to support any longer, then that is a good data point to have and will help us make decisions about how to allocate time here

**Comment by h-vetinari** [comment]
Not speaking for Isuru, but my concern here is that 3.0 _just_ came out, 1.1.1 is an LTS and not going anywhere, and so forcing people to use OpenSSL 3 on python 3.7 (which upstream even doesn't do) is IMO worse than just not supporting py37 + OpenSSL 3.

**Comment by h-vetinari** [comment]
> such that I could again whack-a-mole back-porting patches that maybe fix it?

Oh boy, whack-a-mole indeed: python 3.7 + OpenSSL 3 fails the cryptography test suite on windows.

This is IMO less urgent than fixing OpenSSL 1.1.1, but it shows that the current backports are incomplete in _both_ cases.

> There's only about 5-6 potential patches at play here, I think, but a couple of them are very large.

That number matches my own search a while ago, if you're interested I wrote down some findings [here](https://foss.heptapod.net/pypy/pypy/-/issues/3560#note_163882) and [here](https://foss.heptapod.net/pypy/pypy/-/issues/3560#note_163975) in the context of pypy.

> So it is possible to get a simple one-line test that reproduces this issue

Aside from the invocation above, you could also use the [`downstreams`](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#downstream-tests) feature of conda (an [example](https://github.com/conda-forge/libcxx-feedstock/blob/master/recipe/meta.yaml#L76)) right here in the CI, e.g. adding
```
      downstreams:
        - cryptography
```
to the test section should work out of the box.

**Comment by akrherz** [comment]
> We decided to do both versions because it's going to take some time get all our packages working with openssl 3. So, we need to support both for a while.

I am the least sharp tool in the toolbox, but I was wondering about this and wonder if there is a better approach.  Maybe a new python 3.7 build should be made, without openssl 3 support.  Then within the conda-forge repo, the following would be true.

1.  The newest build of python 3.7 would have a openssl 1.1.1 requirement and thus not default those who automatically get the newest build into something that may be quasi broken with openssl 3 tagging along.
2. Those that have an openssl 3 requirement, would get the older python 3.7 build with openssl 3 "support".

Does that make any sense?  As it stands currently:

```
$ conda create -n py37 python=3.7
...
  openssl            conda-forge/linux-64::openssl-3.0.0-h7f98852_1
  python             conda-forge/linux-64::python-3.7.10-hf930737_104_cpython
...
```

**Comment by h-vetinari** [comment]
>  Maybe a new python 3.7 build should be made, without openssl 3 support.

There are many such builds of python, in fact all 3.7 builds before #499. Indeed, after that PR, there are now two builds per python version (one each for OpenSSL 1.1.1 and 3.0), because OpenSSL is ABI-relevant (in other words, you cannot hotswap the OpenSSL binary without corrupting/crashing the python running on top of it).

For example, installing any of the packages that haven't yet been rebuilt for the 3.0 [migration](https://conda-forge.org/status/#openssl3) (e.g. cryptography) will necessarily pull in the python build against 1.1.1 for the environment to be able to resolve.

That means _most_ applications & environments (anything that requires any package affected by the OpenSSL ABI that hasn't been rebuilt yet) will still pull in OpenSSL 1.1.1, and therefore, the failure of the cryptography test suite looked potentially very impactful. As it stands, it looks like it was a flake, and I think we can go about our merry ways for now (🤞).
