### ISSUE TITLE
Port patches from 3.10 branch to 3.8

### ISSUE THREAD

**Issue by isuruf** [conda-forge/python-feedstock#534]
This would bring in a bunch of changes from 3.10 branch including
- Unvendoring of dependencies in windows
- Removing _CONDA_PYTHON_SYSCONFIGDATA_NAME
- Changing CONDA_DLL_SEARCH_MODIFICATION patch

We did the same for the 3.9 branch, but for a new version of 3.9.
However 3.8 will probably not get a new version, so we might have
to do this for a patch version. Thoughts?

cc @xhochy, @katietz, @chenghlee

**Comment by h-vetinari** [comment]
There have been a few [commits](https://github.com/python/cpython/commits/3.8) since 3.8.12, and based on the release schedule, [irregular](https://www.python.org/dev/peps/pep-0569/#source-only-security-fix-releases) releases will be provided until Oct. 2024 on an as-needed basis.

**Comment by isuruf** [comment]
Done now
