### ISSUE TITLE
Python 3.10 and 3.9 packages are much larger than 3.8

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/python-feedstock#541]
For example, the numpy package
![image](https://user-images.githubusercontent.com/90008/150653104-b8080abd-e83a-4eeb-a47d-0ffb08f3ecec.png)

- 8.1 MB linux-64/numpy-1.22.0-py38h6ae9a64_1.tar.bz2
- 20.4 MB linux-64/numpy-1.22.0-py39h91f2184_1.tar.bz2
- 19.4 MB linux-64/numpy-1.22.0-py310h454958d_1.tar.bz2

Not too sure what it is.

**Comment by hmaarrfk** [comment]
This seems to be an issue with other feedstocks as well (such as imagecodecs) which is why i'm posting here in the python feedstock. It could be a cython issue :/

**Comment by xhochy** [comment]
Seems like we missed to port https://github.com/conda-forge/python-feedstock/blob/3.8/recipe/patches/0006-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch to the new set of patches. Looking at the `asyncpg` builds, we can see that in the master 3.9 build `-g` is not present in the compiler flags while it pops up with 3.10. Rebuiling the 3.9 build with latest 3.9 python build also adds the `-g` flags into the log. 

I'll fix this later in 3.9 and 3.10.

Thanks @fhoehle for pair-coding on this!

**Comment by xhochy** [comment]
Closing this as we have updated the Python versions. @hmaarrfk and @fhoehle feel free to rebuild any packages later today to get smaller sizes again.
