### ISSUE TITLE
Is Python on Windows built by MSVC from the docker image?

### ISSUE THREAD

**Issue by leofang** [conda-forge/python-feedstock#580]
### Comment:

I noticed that conda-forge's Python was [built with vs2017](https://github.com/conda-forge/python-feedstock/blob/134ba25ba2f5696c14060518fafb4aaebfedb544/recipe/conda_build_config.yaml#L7-L10), and for some reason the version `14.29.30133` was used (search [its build log](https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/555791/logs/38)) instead of the ones distributed on conda-forge (`30133` is not an available version). So it seems we're using the docker image's MSVC. Is this expected?

**Comment by isuruf** [comment]
As @h-vetinari said in the issue, we don't distribute the compiler in conda-forge due to licensing reasons.

**Comment by leofang** [comment]
@isuruf Do you mind expanding a bit more on this? I don't follow why license has to do with my question.

**Comment by isuruf** [comment]
We don't distribute MSVC compilers, so we use the ones in the Azure image. (We don't distribute docker images nor do we use docker on windows.)

**Comment by leofang** [comment]
Ah ok got it, right it was not correct to mention docker. But the situation here is basically like nvcc from CUDA.
