### ISSUE TITLE
What is the difference between the libpython-static and python packages?

### ISSUE THREAD

**Issue by peterroelants** [conda-forge/python-feedstock#585]
### Comment:

What is the difference between the `libpython-static` and `python` packages?

In what cases should I use`libpython-static`?

**Comment by isuruf** [comment]
`libpython-static` gives the `libpython3.10.a` static file which is needed only rarely.

**Comment by peterroelants** [comment]
Does this mean that by installing `libpython-static` I can use Python installed by conda independently of any other pre-installed packages (e.g. like in a Docker `FROM scratch `) image?

**Comment by isuruf** [comment]
It only means that you get a `libpython3.10.a` that you can use to link to in your executables embedding python.
