### ISSUE TITLE
Are debug builds supported? 

### ISSUE THREAD

**Issue by nikhilweee** [conda-forge/python-feedstock#594]
### Comment:

I see a `--with-pydebug` option specified in the recipe folder. I wonder what's it for? 
https://github.com/conda-forge/python-feedstock/blob/018b46521412f51cf732a1e4e08e999cb160f6bd/recipe/build_base.sh#L51-L58
Me along with a few others have been on the lookout for a debug build (https://github.com/conda-forge/staged-recipes/issues/4812) and I wonder if this is the way to go?

**Comment by jakirkham** [comment]
It's possible to build locally (as seen above), but we do not currently publish debug packages

**Comment by nikhilweee** [comment]
Is the community interested in reviving #86? Although I don't have much experience writing conda recipes, I am eager to take a shot at it.

**Comment by jakirkham** [comment]
Idk when I've asked other developers about whether a debug Python is useful, have heard they may want to make additional changes to the `python` build itself, use other debug libraries in the build, and/or build other downstream dependencies with changes. Given this, it has been unclear (at least to me) that there is one debug build of Python that would be helpful for these different use cases
