### ISSUE TITLE
Python 3.6 pre-releases

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/python-feedstock#6]
Would be nice to build a pre-release of Python 3.6 for testing.  Perhaps including it in a specific pre-release channel, conda-forge/conda-forge.github.io/#370.  

[Source code for Python 3.6.0a1](https://www.python.org/downloads/release/python-360a1/)

[Python 3.6 release schedule](https://www.python.org/dev/peps/pep-0494/)

[What new in Python 3.6](https://docs.python.org/3.6/whatsnew/3.6.html) might be helpful for writing tests.

**Comment by jakirkham** [comment]
Good idea. Could you please raise this point on this issue ( https://github.com/conda-forge/conda-forge.github.io/issues/147 ) for handling dev builds?

**Comment by jjhelmus** [comment]
3.6.0a3 was released with PR #45, will continue to keep this issue open for future release.  

The remaining release schedule are as follows:

```
3.6.0 alpha 4: 2016-08-15 (was 08-08)
3.6.0 beta 1: 2016-09-12 (was 09-07)
(No new features beyond this point.)

3.6.0 beta 2: 2016-10-03
3.6.0 beta 3: 2016-10-31
3.6.0 beta 4: 2016-11-21
3.6.0 candidate 1: 2016-12-05
3.6.0 candidate 2 (if needed): 2016-12-12
3.6.0 final: 2016-12-16
```

**Comment by jakirkham** [comment]
Just out of curiosity, have you tried building anything else with that Python? I'd be interested to know what works or doesn't and any things to watch out for.

**Comment by jjhelmus** [comment]
I build [pip](https://anaconda.org/jjhelmus/pip/files) and [setuptools](https://anaconda.org/jjhelmus/setuptools) for Python 3.6 so that `pip` can be used to bootstrap and environment but that is all I've tried so far.  Once release candidates are out (December) it would be good to start testing the rest of the conda build stack so that we can start rebuilding everything from the ground up.

**Comment by ZetaHunter** [comment]
@jjhelmus beta 2 has been released recently, mind taking a look and updating your builds?

**Comment by jjhelmus** [comment]
Working on the beta 2 release in #82

**Comment by jreback** [comment]
seems 3.60b4 is out, can someone trigger a build for the last pre-release?

**Comment by jjhelmus** [comment]
`3.6.0b4` build was added in PR #94, should be uploaded to Anaconda.org shortly.

**Comment by jakirkham** [comment]
Yep, all of them appear to be up there and ready to go.

**Comment by jreback** [comment]
thanks! looks great.

**Comment by jjhelmus** [comment]
Python 3.6.0 has been released so there will be no further pre-releases.  Closing

**Comment by ajasja** [comment]
@jjhelmus Hi! Just wondering about python 3.6.1rc1. Does that count as a pre release as well?

**Comment by jjhelmus** [comment]
@ajasja It is a pre-release but given that it is not a major version release I was not planning on making a package through conda-forge.  I would be happy to review and merge a pull request which adds 3.6.1rc1 to the `prerelease` branch of this feedstock if someone wanted to put this together.
