### ISSUE TITLE
Use `expat` package

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/python-feedstock#607]
Currently `python` builds with a vendored `expat` library. It would be good to replace this with our own `expat` package.

**Comment by scdub** [comment]
This would be nice, as it does take a non-trivial amount of time for a CPython patch release to be cut with the changes. The [PR for 2.5.0](https://github.com/python/cpython/issues/98739) went into CPython about 40 days ago but a release hasn't yet been cut for any of the security branches. The `pyexpatns.h` file would need to be kept in sync, possibly other "outside" information but should be manageable.

**Comment by isuruf** [comment]
> The pyexpatns.h file would need to be kept in sync, possibly other "outside" information but should be manageable.

Can you give more details on this? We started using system expat with 3.11.1 today.

**Comment by jakirkham** [comment]
The Python 3.11 linked PR ( https://github.com/python/cpython/pull/98784 ) from that issue doesn't appear to change that file

The last change to the `pyexpatns.h` file ( https://github.com/python/cpython/commit/6312c1052c0186b4596fc45c42fd3ade9f8f5911 ) appears to add new `#define`s. Searching for [one of the newer `#define`s doesn't show anything outside `pyexpatns.h`]( https://github.com/search?q=repo%3Apython%2Fcpython+PyExpat_testingAccountingGetCountBytesDirect&type=code ). How are these used?

**Comment by scw** [comment]
I believe the need for this file's changes is described [in the header for `pyexpatns.h`](https://github.com/python/cpython/blob/main/Modules/expat/pyexpatns.h#L3-L35), these symbols should be synced at releases of libexpat which introduce new symbols so the namespaced redefined copies Python uses are kept in sync.

**Comment by isuruf** [comment]
@scw, I don't understand what you are trying to say here. What do you think should be done here?

**Comment by scw** [comment]
> @scw, I don't understand what you are trying to say here. What do you think should be done here?

I _think_ it should be possible to dynamically regenerate `pyexpatns.h` as needed. Probably what would be even better here is to skip this enterprise of trying to sync it in the source tree, and instead rely directly on the package: CPython does accept a `--with-system-expat` [configuration option](https://github.com/python/cpython/blob/main/configure.ac#L3986) but unfortunately that looks like it only applies on POSIX systems.

**Comment by isuruf** [comment]
We use `--with-system-expat` on Unix and we patch the windows build system to use our copy of expat to link to. We don't regenerate `pyexpatns.h` though.

**Comment by scw** [comment]
@isuruf Ah got it! I think this issue can probably be closed then, `pyexpatns.h` is only used with the internal copy of expat. The idea behind namespacing the symbols is for situations where other libraries are also embedding expat and  those symbols can have collisions, as described in the header:
 - you embed Python in some app
 - the app dynamically loads libexpat of version X
 - the embedded Python imports pyexpat (which was built against ibexpat version X+n)

 Dynamically linking here seems it would more directly address this issue, not to mention that someone using conda for development would be expected to abide by the ABI compatibility specified by the package pinning.

**Comment by isuruf** [comment]
Thanks for explaining.
