### ISSUE TITLE
Building Python 3.13 dev releases + no GIL

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/python-feedstock#658]
Python 3.13 has 2 alpha releases and a 3rd one due out in a week. Here's [the release schedule]( https://peps.python.org/pep-0719/ ) for more details

Of particular note, [the `--disable-gil` build flag]( https://docs.python.org/3.13/using/configure.html#cmdoption-disable-gil ) was added, which should allow building a Python with the GIL disabled. It's important to note that this mode is [not ABI compatible with the mode that keeps the GIL]( https://peps.python.org/pep-0703/#python-build-modes ). So any extension module built with Python would need to be rebuilt with the no GIL interpreter to be used with it. That said, in no GIL mode there is an environment variable to toggle GIL usage, [`PYTHONGIL`]( https://peps.python.org/pep-0703/#pythongil-environment-variable ). Eventually the ABI stability will be addressed, but this is still several Python releases away. So we will need to decide what to do before then

Naively would propose building both build modes

We may also want to explore building a couple common libraries (like NumPy, SciPy, scikit-learn) to try with. IIRC some libraries already have fixes included for no GIL. So those seem like a preferable starting point

There is [some interest in building out packages with Anaconda]( https://peps.python.org/pep-0703/#distribution ). So think we will want to coordinate

Would be interested to hear thoughts on this 🙂

**Comment by ovo-Tim** [comment]
Hi, I'm trying to [build NoGil](https://github.com/ovo-Tim/nogil-recipe). I met some problems while building for Linux on github action.
Can you have a look? https://stackoverflow.com/questions/77895008/build-cpython-failed-on-github-action-output-tons-of-error-messages

Also, I have built successfully on my own computer. See: https://anaconda.org/ovo-tim/nogil

**Comment by xhochy** [comment]
@ovo-Tim Can you make a pull request to the feedstock with your changes? Then we could integrate that here (and help you with CI)

**Comment by ovo-Tim** [comment]
@xhochy Should I create a new branch, or just pull up github action?

**Comment by xhochy** [comment]
Please make a pull request with a branch on your repository and keep using Azure Pipelines. We don't want to use GitHub Actions for package builds.

**Comment by ovo-Tim** [comment]
@xhochy Hi, you may should create a branch. Than I wil make a pull request with this new branch. (I think I don't have permission to create a branch on this repository, I am not a git expert.)

**Comment by xhochy** [comment]
No, please fork and make a pull request from that fork. GitHub has good documentation on how to contribute via a pull request to another repository. Please have a look at that.

**Comment by h-vetinari** [comment]
Adding to the excitement (disruption?) of 3.13, it now [has](https://docs.python.org/dev/whatsnew/3.13.html#experimental-jit-compiler) a build-time dependence on LLVM.

**Comment by jakirkham** [comment]
Indeed in typical Python fashion there is a poem to go with it: https://github.com/python/cpython/pull/113465

**Comment by h-vetinari** [comment]
Haha, nice. :)



> @h-vetinari: [...] build-time dependence on LLVM (haven't checked yet which bits).

Needs clang 16 and `llvm-readobj`, details [here](https://github.com/brandtbucher/cpython/blob/justin/Tools/jit/README.md). Cross-compilation should work, "since the JIT is built for the host platform" - though I don't see how that would then imbue the target architecture with a working JIT... 🤔

**Comment by xhochy** [comment]
> though I don't see how that would then imbue the target architecture with a working JIT... 🤔

The copy-and-patch JIT actually generates Assembly at compile-time and only "patches" that assembly together at runtime. There is no compilation happening at runtime.

**Comment by h-vetinari** [comment]
Thanks for the explanation @xhochy! But wouldn't those assembly pieces have to be specific to the target architecture? I guess that would work if the JIT on host can target another architecture - in that case I just got confused by "JIT built only on host" not clearly implying that.

**Comment by jakirkham** [comment]
There is now an environment variable/flag to configure whether the GIL is enabled in Pythons built with `--disable-gil`

xref: https://github.com/python/cpython/pull/116338

**Comment by rgommers** [comment]
Since there are now conda-forge packages for free-threaded Python as well as some commonly used packages like `numpy`, `pyzmq`, and `psutil`, I think this issue can be closed?

> There is [some interest in building out packages with Anaconda](https://peps.python.org/pep-0703/#distribution). So think we will want to coordinate

Note that those packages are also available in the `ad-testing` channel. Install instructions for both Conda-forge and `ad-testing` can be found at https://py-free-threading.github.io/installing_cpython/#multi-platform-package-managers.
