### ISSUE TITLE
Other build flags?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/python-feedstock#66]
Noted these additions made by Travis CI in PR ( https://github.com/travis-ci/cpython-builder/pull/15 ). Was curious if it would be worthwhile to add some of these other options like `--with-wide-unicode`, `--enable-loadable-sqlite-extensions`, or `--with-computed-gotos`.

**Comment by jjhelmus** [comment]
The [anaconda-recipes Python 3.5](https://github.com/ContinuumIO/anaconda-recipes/blob/master/python-3.5/build.sh) build does not include these flags and I'm hesitant to stray to far from this for our build and risk causing incompatibilities between the two packages.

**Comment by xmnlab** [comment]
--enable-loadable-sqlite-extensions [1] tag would be nice. Is it possible to be included?

[1] https://docs.python.org/3/library/sqlite3.html#f1

**Comment by jakirkham** [comment]
@msarahan , how do you feel about these options?

**Comment by jakirkham** [comment]
To update this issue a bit, we since added `--enable-loadable-sqlite-extensions` to all builds.

AFAIK `--with-computed-gotos` is the default option (at least according to [CPython issue 9203]( https://bugs.python.org/issue9203 )) and was backported to CPython 2.7 as [noted here]( https://mail.python.org/pipermail/python-dev/2015-May/140321.html ).

As to Unicode support, appears all of our builds except a couple macOS builds ( https://github.com/conda-forge/python-feedstock/issues/224 ) are using UCS4. Would be nice to standardize the rest of the macOS builds.

Given this will close this issue out as the bulk of these flags are already included at this point. Hopefully we can sort out UCS4 support for macOS Python 2.7.
