### ISSUE TITLE
No linux-aarch64 builds for Python 3.10.14

### ISSUE THREAD

**Issue by jrbourbeau** [conda-forge/python-feedstock#683]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

When https://github.com/conda-forge/python-feedstock/pull/682 was merged, it looks like corresponding CI build where linux-aarch64 packages are built and uploaded failed for some reason https://app.travis-ci.com/github/conda-forge/python-feedstock/jobs/619463766. I don't see any build logs there, so I'm not sure if it's an actual issue, or just a transient one (e.g. http error or something) 

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by jrbourbeau** [comment]
That did the trick -- thanks as always @jakirkham!

**Comment by jakirkham** [comment]
Happy to help!

Also please remember packages mirror to CDN. So even if they are uploaded, it may take some time before they are available for install
