### ISSUE TITLE
Build against xz 5.2.2

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/python-feedstock#7]
The latest release of [xz](http://tukaani.org/xz/) is version 5.2.2.  A build should be created which uses this version of xz.

**Comment by pelson** [comment]
Agreed. The problem is bigger than Python, but we have been holding out for the Python recipe in order to move forwards with the xz version (as per the comment in https://github.com/conda-forge/staged-recipes/wiki/Pinned-dependencies).

**Comment by ocefpaf** [comment]
Closed by #38 

@jjhelmus we still need to do 2.7 and 3.4, right?

PS: Is this the right branch for 2.7?

https://github.com/conda-forge/python-feedstock/blob/2.0/recipe/meta.yaml#L3

**Comment by jjhelmus** [comment]
There is no conda-forge Python 2.7 and 3.4 builds. Although 3.4.5 is nearly ready, #40, and I'm working on a 2.7.12 PR. I'll update the pins appropriately for both of these.

The `2.0` branch is specifically for Python 2.0, #37, mostly out of my own curiosity if such a thing could be built.

**Comment by ocefpaf** [comment]
Thanks for the clarification @jjhelmus! So this is safe to close then, right?

**Comment by jjhelmus** [comment]
> So this is safe to close then, right?

Yes.
