### ISSUE TITLE
vc14_runtime Dependency

### ISSUE THREAD

**Issue by JoelStansbury** [conda-forge/python-feedstock#710]
### Comment:

Hello,

I'm a bit confused about the vc14_runtime dependency which is included for win-64.

1. Are you aware of an exception that would enable people to distribute this package `conda-forge/python` and dependencies (`vc14_runtime`)?
    > for example, as a `conda-pack` archive or a `constructor` installer which includes `conda-forge/python`

2. It appears that vs2015_runtime is supposed to be backward-compatible, and has a permissive license... Is it possible to replace `vc14_runtime` with `vs2015_runtime`?

### Additional Information
- `conda-forge/python` requires `vc14_runtime` 
   https://conda-metadata-app.streamlit.app/?q=conda-forge%2Fwin-64%2Fpython-3.13.0rc2-hf5aa216_100_cp313.conda
   (it also requires `ucrt` which is less restrictive, but could still be problematic)

- The license for this file is Proprietary and not distributable, yet mambaforge ships it because conda-forge/python requires it.
This can be seen by exploring the `.exe` file as an archive and reading the license file located at 
`Miniforge3-Windows-x86_64.exe\pkgs\vc14_runtime-14.40.33810-hcc2c482_20.conda\pkg-vc14_runtime-14.40.33810-hcc2c482_20.tar.zst\pkg-vc14_runtime-14.40.33810-hcc2c482_20.tar\info\licenses\`
  ```
  You may not.
  ...
  share, publish, rent or lease the software, or provide the
  software as a stand-alone offering for others to use, or
  transfer the software or this agreement to any third party.
  ```

- Interestingly, miniconda does not ship the vc14_runtime package because the python package hosted on `pkgs/main` depends on vs2015_runtime instead, which contains a permissive license.
https://conda-metadata-app.streamlit.app/?q=pkgs%2Fmain%2Fwin-64%2Fpython-3.12.3-h1d929f7_1.conda

**Comment by isuruf** [comment]
vc14_runtime and vs2015_runtime are the same and has the proprietary license. It was a package rename. Metadata in `vs2015_runtime` is wrong. It's certainly not an issue in the python package. You can open an issue with vc-feedstock if you need further clarification.

**Comment by JoelStansbury** [comment]
The README.md for vc feedstock says that `vs2015_runtime` is licensed as BSD-3
while `vc14_runtime` is proprietary.

I see what you mean about the metadata though... the license string appears to be empty

**Comment by JoelStansbury** [comment]
They are not exactly the same... `vs2015_runtime` does not contain `vcamp140.dll` 
Otherwise `vs2015_runtime` appears to contain all of `vc14_runtime`

**Comment by isuruf** [comment]
> The README.md for vc feedstock says that vs2015_runtime is licensed as BSD-3

`vs2015_runtime` in conda-forge is empty and is a meta-package that requires `vc14_runtime`. So, it can be whatever license we need it to be.
