### ISSUE TITLE
recall command

### ISSUE THREAD

**Issue by marqh** [conda-forge/python-feedstock#72]
On a fresh install of python from conda-forge
```
The following NEW packages will be INSTALLED:

    ncurses:    5.9-9         conda-forge
    openssl:    1.0.2j-0      defaults   
    pip:        8.1.2-py27_0  conda-forge
    python:     2.7.12-1      conda-forge
    readline:   6.2-2         defaults   
    setuptools: 27.2.0-py27_0 defaults   
    sqlite:     3.13.0-1      conda-forge
    tk:         8.5.19-0      conda-forge
    wheel:      0.29.0-py27_0 conda-forge
    zlib:       1.2.8-3       conda-forge

```

My "up arrow" key returns the string

```
>>> ^[[A
```
right arrow
```
>>> ^[[C
```
etc. ...
at the command prompt, not the previous command.  Not as effect I get with the system python

Any ideas on how could this be different please?

thank you
marqh

**Comment by jjhelmus** [comment]
This behavior is caused by mixing packages from the `defaults` and conda-forge` channels.  Using the `readline` package provided by the `conda-forge` channel should fix this issue.  This can be accomplished using the command: `conda install -c conda-forge readline`.

**Comment by marqh** [comment]
that worked a treat. thank you @jjhelmus
