### ISSUE TITLE
Windows builds depend on xorg

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/python-feedstock#720]
After some iteration in #706, we ended up porting variants of that to the various branches, e.g. https://github.com/conda-forge/python-feedstock/commit/3052d25823f4ef46b433e5400ef811ee337cd41d on main.

However, the run-export from `xorg-libx11` doesn't seem to get ignored as specified
https://github.com/conda-forge/python-feedstock/blob/f0d9be92d42c86c6fef19bb293d1dfce247a1d95/recipe/meta.yaml#L91-L95

on windows, leading to an `xorg-libx11 >=1.8.9,<2.0a0` dependency for our windows builds.

Presumably we should add a selector to
https://github.com/conda-forge/python-feedstock/blob/f0d9be92d42c86c6fef19bb293d1dfce247a1d95/recipe/meta.yaml#L171-L172

(and maybe raise a conda-build issue)

CC @isuruf

**Comment by h-vetinari** [comment]
Ah, I see the issue. `ignore_run_exports_from:` has a selector 🤦

**Comment by isuruf** [comment]
Thanks for the PR. Keeping this open until backports are in.

**Comment by h-vetinari** [comment]
* [ ] #723
* [ ] #724
* [ ] #725 
* [ ] #726 
* [ ] #727
