### ISSUE TITLE
Debug builds?

### ISSUE THREAD

**Issue by wesm** [conda-forge/python-feedstock#73]
Any idea how much work it would be to have a, say, `3.5-debug` Python version? Maybe this is already available somewhere.

**Comment by tadeu** [comment]
@wesm Also take a look at https://github.com/conda-forge/staged-recipes/issues/1593 and https://github.com/conda-forge/staged-recipes/pull/961

**Comment by dfroger** [comment]
Just created the pull request #86 about this

**Comment by jakirkham** [comment]
This is a great idea that we should really revive (especially as the tooling has caught up a bit). Raised issue ( https://github.com/conda-forge/conda-forge.github.io/issues/544 ) to discuss how we do split packages and generate things like debug builds as products.

**Comment by jakirkham** [comment]
@msarahan, do you know if any work has been done on this front in `defaults`? What recommendations do you and/or others have in terms of building and selecting between debug and non-debug builds of `python` both in downstream builds and `conda` installs? Are there options that `conda-build` 3 provides that would be helpful for this effort?

**Comment by jakirkham** [comment]
It's worth noting as of Python 3.8 the interpreter includes all debug symbols. So a separate debug build is no longer needed for 3.8+.

ref: https://docs.python.org/3/whatsnew/3.8.html#debug-build-uses-the-same-abi-as-release-build

cc @conda-forge/core (for visibility)

**Comment by jakirkham** [comment]
With some of the recent work on PyPy, this seems more doable. Raising issue ( https://github.com/conda-forge/python-feedstock/issues/73 ) to discuss.

**Comment by mingwandroid** [comment]
I did some work for debug builds on Windows on Python 3.8. The ABI is not exactly the same. There is one symbol of difference ("CreateModule2" gets suffixed "Refcounted" or something like that).

I used this when I was looking into a Python 3.8 issue on Windows with LIEF. It builds a load of stuff with a huge amount of debug info using a very hacky batch file. To change what gets built, see:
If anyone has time, this is how to run it. You need my latest WIP conda-build branch too! 
```
conda activate
cd %TEMP%
mkdir debug-py-win
cd debug-py-win
git clone https://github.com/AnacondaRecipes/python-feedstock
git clone https://github.com/mingwandroid/conda-build -b 10-Add-build-id-pat-option
pushd conda-build
  python setup.py develop
popd
curl -SLO https://raw.githubusercontent.com/AnacondaRecipes/aggregate/master/conda_build_config-dbg_c-dbg_py_win-32.yaml
curl -SLO https://raw.githubusercontent.com/AnacondaRecipes/aggregate/master/conda_build_config-dbg_c-dbg_py_win-64.yaml
curl -SLO https://raw.githubusercontent.com/AnacondaRecipes/aggregate/master/conda_build_config-dbg_win-32.yaml
curl -SLO https://raw.githubusercontent.com/AnacondaRecipes/aggregate/master/conda_build_config-dbg_win-64.yaml
curl -SLO https://raw.githubusercontent.com/AnacondaRecipes/aggregate/master/conda_build_config-win-32.yaml
curl -SLO https://raw.githubusercontent.com/AnacondaRecipes/aggregate/master/conda_build_config-win-64.yaml
python-feedstock\build-locally-debug.bat
```

I've only ever run this on my own machines and without `conda-forge` in my channel list as I was debugging this against `defaults`.

To tweak what gets built, check this block: https://github.com/AnacondaRecipes/python-feedstock/blob/master/build-locally-debug.bat#L3-L21

I think Unix Python debug builds would be a great idea. For Windows, I'd like us to do something different which is to heed the upstream maintainer's advice that we should make a release-with-debug-symbols build as our python 3.8 debug builds, for now at least.

Cheers!

**Comment by jakirkham** [comment]
Thanks Ray! 😄

> I did some work for debug builds on Windows on Python 3.8. The ABI is not exactly the same. There is one symbol of difference ("CreateModule2" gets suffixed "Refcounted" or something like that).

Did this get raised upstream?

**Comment by mingwandroid** [comment]
Only in the sense that Steve Dower is the upstream main Windows Python maintainer.
 I can dig out links to recent issues if you wish, but the declaration of ABI-compat was premature without the Windows caveats. There's also the issue of linking to the debug UCRT runtime. This is why my test script builds each subproject against each python.

**Comment by mingwandroid** [comment]
I guess at Python 3.9 there might be some official debuggable-release build config.. maybe! Or we should put in the work and submit a PR.

**Comment by jakirkham** [comment]
I see. Well at the bare minimum and issue would be useful to aid prioritization/visibility.
