### ISSUE TITLE
Remove Windows dependencies pulled in using SVN

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/python-feedstock#8]
The windows build pulls in various third party libraries (zlib, openssl, bzip2, tcl/tk, sqlite, and xz) using SVN.  Providing these libraries as conda packages and linking against these would be preferred.

**Comment by msarahan** [comment]
Working on this. Thanks for the reminder.

**Comment by jakirkham** [comment]
Any news, @msarahan?

**Comment by msarahan** [comment]
My memory is that this was working well in https://github.com/conda-forge/python-feedstock/pull/19 - but the tests there are all failing.  I'll revisit it and see what state it is in.

**Comment by jakirkham** [comment]
Is this something we are still interested in?

**Comment by jjhelmus** [comment]
As discussed in #19 this is still of interested.

**Comment by isuruf** [comment]
Done in 3.9 and 3.10
