### ISSUE TITLE
Python 2.7 from conda-forge breaks cython builds using mingw

### ISSUE THREAD

**Issue by synapticarbors** [conda-forge/python-feedstock#81]
Moving this from the conda-forge google group to here on @pelson's suggestion:
https://groups.google.com/forum/#!topic/conda-forge/vMHyvb3ogK4

I came across a bug on Windows where the python 2.7 build causes compilation failures when using cython with mingw. I create an conda environment:

conda install -n foo -c conda-forge python libpython mingw cython

And then I try to compile a cython .pyx file that's something trivial like:

test.pyx: 

```
class A(object):
pass
cdef double func(int x):
return 1.3 * x
```

Then if I run:

cythonize -bi test.pyx

I get the following error:

```
Compiling C:\Users\josh\Desktop\test.pyx because it changed.
[1/1] Cythonizing C:\Users\josh\Desktop\test.pyx
running build_ext
building 'test' extension
C:\Users\josh\Miniconda2\envs\foo\Scripts\gcc.bat -mdll -O -Wall -IC:\Users\josh\Miniconda2\envs\foo\include -IC:\Users\josh\Miniconda2\envs\foo\PC -c C:\Users\josh\Desktop\test.c -o c:\users\josh\des
ktop\test.o
C:\Users\josh\Desktop\test.c:659:15: warning: '__pyx_f_4test_func' defined but not used [-Wunused-function]
writing c:\users\josh\desktop\test.def
C:\Users\josh\Miniconda2\envs\foo\Scripts\gcc.bat -shared -s c:\users\josh\desktop\test.o c:\users\josh\desktop\test.def -LC:\Users\josh\Miniconda2\envs\foo\libs -LC:\Users\josh\Miniconda2\envs\foo\PC
build\amd64 -LC:\Users\josh\Miniconda2\envs\foo\PC\VS9.0\amd64 -lpython27 -lmsvcr90 -o C:\Users\josh\Desktop\test.pyd
c:\users\josh\desktop\test.o:test.c:(.text+0x307): undefined reference to `__imp_Py_InitModule4'
collect2.exe: error: ld returned 1 exit status
error: command 'C:\\Users\\josh\\Miniconda2\\envs\\foo\\Scripts\\gcc.bat' failed with exit status 1
```

If I then go back and replace the python in the environment (which was from conda-forge) using:

conda install -c defaults python

Then the code correctly compiles. 

Some google searches say that you need to define `MS_WIN64`. I'm not sure that it is totally fair to say that the conda-forge build "breaks" compilation using mingw, but it is nonetheless surprising when you pull in python from conda-forge after using the defaults version and code compilation starts breaking where in previously worked. I'm not sure if conda-forge should or can adjust some build parameter so that it plays nicely with the defaults libpython/mingw. 

Josh

**Comment by jjhelmus** [comment]
My initial guess is this difference might be caused by the [win-cygwin.patch](https://github.com/ContinuumIO/anaconda-recipes/blob/master/python-2.7/win-cygwin.patch) that the `defaults` Python is likely applying.  I'll investigate this when I have some free time and am by a windows machine.  

@synapticarbors If you get to it first can you see if the `Lib/distutils/cygwinccompiler.py` files are different between the two Pythons and if applying that patch to the conda-forge version solves the issue?

**Comment by jjhelmus** [comment]
@synapticarbors I tried to replicate this issue in a Windows VM and was able to compile the test file with both the python 2.7 package from `default` and from `conda-forge` without issue.  

Can you provide additional details on your setup, specifically if you are on a 32 bit or 64 bit platform. I only tested on a 32-bit system.

**Comment by jjhelmus** [comment]
I able to replicate this on the 64-bit Windows machine.  Replacing the `Lib/distutils/cygwinccompiler.py` with the one from the `defaults` channel results in a working Cython built.  I believe adding the above mentioned patch to the windows build should fix the issue.

**Comment by jakirkham** [comment]
Is this still an issue, @synapticarbors?

**Comment by isuruf** [comment]
2.7 is dropped now
