### ISSUE TITLE
Python 3.6.0b3 in conflict with itself

### ISSUE THREAD

**Issue by jorisvandenbossche** [conda-forge/python-feedstock#85]
Maybe I am trying to install the beta version in the wrong way, but when trying to install the beta version, I get:

```
joris@joris-XPS-13-9350:~/scipy$ conda create -n py36 python=3.6.0b3 -c conda-forge/label/prerelease
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .............
Solving package specifications: ....

The following specifications were found to be in conflict:
  - python 3.6.0b3*
Use "conda info <package>" to see the dependencies for each package.
```

The same if I just specify `3.6` instead of `3.6.0b3`

This is on Linux (Ubuntu, 64 bit)

**Comment by ocefpaf** [comment]
I believe you need to add `add_pip_as_python_dependency: false` to your `.condarc` to install that version. @jjhelmus can probably say more.

**Comment by jorisvandenbossche** [comment]
Yes, that does the trick! Thanks a lot @ocefpaf 

And indeed, if you install py35, you see that there are some packages like pip installed by default that depend on the python version. 
But the error message of `conda` could be a bit better :-)

**Comment by jjhelmus** [comment]
> But the error message of conda could be a bit better

Agreed, but there is nothing the feedstock can do about this.  You could report this as an issue to the conda and see if it gets any traction.  I believe more verbose conflict details is being worked on.

One thing that could be done would be to do a  Python 3.6 release of pip/setuptools/wheel on the `conda-forge` channel with the same label as the Python 3.6.0 pre-release.  With would require a bit of customization of the feedstocks but I think could be done.
