### ISSUE TITLE
Remove need for OS X failed extension hack

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/python-feedstock#9]
Currently a hack is being use to properly build some of the OS X Python extension modules.  Specifically, during the `make` command the build script checks to see if each extension module is importable.Those that [fail are renamed and not copied into the correct location](https://travis-ci.org/conda-forge/python-feedstock#L1609-L1628).  To get these modules to work the conda build script [explicitly copies the files into the correct location](https://github.com/conda-forge/python-feedstock/blob/27f32c83253a023b556964b2f0b11eb5f3847ef8/recipe/build.sh#L26-L38).  The post build step adjusts the library search paths in these extensions and so that they are importable, which is explicitly tested by [`run_tests.py`](https://github.com/conda-forge/python-feedstock/blob/27f32c83253a023b556964b2f0b11eb5f3847ef8/recipe/run_test.py).

I think these are failing because the system libraries are shadowing the conda installed libraries.  Adjusting the rpath or library search path during the build may solve this issue.

**Comment by jakirkham** [comment]
Excellent. Thanks for explaining this.

I have seen this problems before. Will take a look through past build notes and see if I can't drum up some ideas for how we fix this.

**Comment by jakirkham** [comment]
So, I tried to fix this, but it turns out the compiler I am using runs into a Python [bug]( https://bugs.python.org/issue24844 ).
